### PR TITLE
introduce virtual socket

### PR DESCRIPTION
**Pull request by torus**
Essentially, this patch just replaces `socket` with a new class `<virtual-socket>`, which allows you to implement any "socket-like" object on your application. By default, a `<virtual-socket>` behaves just like a socket, but you can create a class derived from this and modify the behavior.

Possible applications:
- alternative low-level layer implementation (ie. replacing `start-http-server` with something else)
- unit testing without running a separate server process

### CODE REVIEW

**Comment by shirok** [comment]
I'd like to generalize it and incorporate into Gauche itself (probably something ilke `<connection>`).  Another potential application of such generic interface is TLS; rfc.http has a switching layer depending on whether the connection is direct or secure; if we can provide connection interface in both sockets and tls it'd be cleaner.

So far one thing to consider is the semantics of accept.  There are two possible interpretations---the accept action waits on a raw socket, and returns a newly created instance of `<connection>`, or we let accept method of `<conneciton>` to handle it entirely.  TLS "wraps" on exising socket so it fits the former model.  In gauche-violet you do similar things (the "accept" action is effectively handled in libuv and makiki handler just receives a virtual socket that's already connected to the "client").  I wonder if I should provide the latter method in `<connection>`, or just let the user handle the accept part and `<connection>` is purely a peer-to-peer connection.

**Comment by torus** [comment]
Thank you for the comment!
Indeed TLS is an interesting example.

I didn't come up with the latter approach, but it sounds more straightforward to me. Actually, I felt a bit odd when I was ["virtualizing" the virtually accepted socket again](https://github.com/shirok/Gauche-makiki/pull/4/commits/eefff1175a9b51485249ad4705b32dde7e27e6cb#diff-cea8bbd3e0b9c1b4b3dad1500a9e043aR649). I felt it might be a leaky abstraction.

**Comment by shirok** [comment]
In HEAD of Gauche, I made `<socket>` a subclass of `<connection>`.  The interface of `<connection>` is defined in `gauche.connection` module (`lib/gauche/connection.scm`)

In Gauche-makiki, I created a `use-connection` branch, which uses connection interface within `handle-client`.  If you subclass `<connection>` and defines appropriate methods, then you should be able to pass it to `handle-client` in the second argument.  Could you try it?

**Comment by torus** [comment]
Sure thing!

**Comment by torus** [comment]
It's working great! 👍

**Comment by shirok** [comment]
Cool.
So far, I plan to leave out "connect" and "accept" operation from `<connection>` interface; those operations tend to require knowledge of the layer below, so it's difficult to generalize.  We can add them later if we need.

**Comment by torus** [comment]
It's perfect for me!

**Comment by shirok** [comment]
It seems gauche.connection works for this purpose, I close this PR.

**Pull request closed without merging**
